// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAptmDqAqAQazctC9xuUsVFUVIjz8kICUI',
    appId: '1:359362088897:web:37de2801354d9ede10a940',
    messagingSenderId: '359362088897',
    projectId: 'mpm-connect-prod',
    authDomain: 'mpm-connect-prod.firebaseapp.com',
    storageBucket: 'mpm-connect-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_1Yq74NUno4K7Ez6MnLmdeqgrDKrzdQ',
    appId: '1:359362088897:android:9b609780a7e8246c10a940',
    messagingSenderId: '359362088897',
    projectId: 'mpm-connect-prod',
    storageBucket: 'mpm-connect-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYagW4_PLgle_PQULjp1LAb4QU45W70k',
    appId: '1:359362088897:ios:2443bb7961229ef610a940',
    messagingSenderId: '359362088897',
    projectId: 'mpm-connect-prod',
    storageBucket: 'mpm-connect-prod.firebasestorage.app',
    iosBundleId: 'com.mpm.mpmConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMYagW4_PLgle_PQULjp1LAb4QU45W70k',
    appId: '1:359362088897:ios:2443bb7961229ef610a940',
    messagingSenderId: '359362088897',
    projectId: 'mpm-connect-prod',
    storageBucket: 'mpm-connect-prod.firebasestorage.app',
    iosBundleId: 'com.mpm.mpmConnect',
  );
}
